# Generated by Django 4.1.2 on 2022-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
