# Generated by Django 4.1.2 on 2022-11-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_point', '0002_alter_cotizacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.IntegerField(default=9, editable=False),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('agnio', 'numero'), name='unique_cotizacion'),
        ),
    ]
