# Generated by Django 4.1.2 on 2022-11-22 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_services_management', '0007_remove_servicio_descripcion_servicio_nombre_and_more'),
        ('customers_management', '0009_alter_cliente_tipo_cliente_unique_document'),
        ('sales_point', '0003_alter_cotizacion_numero_cotizacion_unique_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('cantidad_item', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='customers_management.cliente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha / Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.IntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='DetalleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('id_detalle_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_point.detallecotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='id_cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_point.cotizacion'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='item',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='product_services_management.item'),
        ),
    ]
