# Generated by Django 4.1.2 on 2022-11-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_management', '0009_alter_cliente_tipo_cliente_unique_document'),
        ('product_services_management', '0008_item_tipo'),
        ('sales_point', '0004_detallecotizacion_cotizacion_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers_management.cliente'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='id_cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_point.cotizacion'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_services_management.item'),
        ),
    ]
