# Generated by Django 4.1.2 on 2022-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_point', '0005_alter_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='total',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='descuento_item',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
