# Generated by Django 4.1.2 on 2022-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_point', '0006_remove_cotizacion_subtotal_remove_cotizacion_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='agnio',
            field=models.IntegerField(default=2022, editable=False, verbose_name='Año'),
        ),
    ]
