# Generated by Django 4.1.2 on 2022-10-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_services_management', '0002_alter_categoria_estado_alter_impuesto_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_services_management.item'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='codigo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_services_management.item'),
        ),
    ]
