# Generated by Django 4.1.2 on 2022-11-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_services_management', '0003_alter_producto_codigo_alter_servicio_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
