# Generated by Django 4.1.2 on 2022-11-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_services_management', '0004_rename_descripcion_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='codigo',
        ),
    ]
