# Generated by Django 4.1.2 on 2022-11-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_services_management', '0005_remove_item_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
