# Generated by Django 4.1.2 on 2022-11-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services_management', '0007_remove_servicio_descripcion_servicio_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Servicio'), (2, 'Articulo')], default=1),
            preserve_default=False,
        ),
    ]
