# Generated by Django 4.1.2 on 2022-11-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BinaryField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddocumento', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('apellido1', models.CharField(max_length=15)),
                ('apellido2', models.CharField(max_length=15, null=True)),
                ('telefono', models.CharField(max_length=12, null=True)),
                ('direccion', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers_management.cliente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_management.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.BigIntegerField(unique=True)),
                ('razon_social', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers_management.cliente')),
            ],
        ),
    ]
