# Generated by Django 4.1.2 on 2022-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.BinaryField(default=0, editable=True),
        ),
    ]
