# Generated by Django 4.1.2 on 2022-11-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_management', '0002_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.BooleanField(default=True),
        ),
    ]
