# Generated by Django 4.1.2 on 2022-11-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_management', '0003_alter_cliente_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='iddocumento',
            field=models.CharField(default='40222878684', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers_management.tipodocumento'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
