# Generated by Django 4.1.2 on 2022-11-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_management', '0008_alter_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Empresa'), (2, 'Persona')], default=2),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('iddocumento', 'tipo_documento'), name='unique_document'),
        ),
    ]
